name: "Backend"
on:
  pull_request:
  push:
jobs:
  build-backend:
    name: Build and push docker image
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: build image
      run: |
        cd backend
        ./buildimage.sh
    - name: gcr.io login
      uses: actions-hub/gcloud@master
      with:
        args: "auth print-access-token > token.txt"
      env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_APPLICATION_CREDENTIALS }}
    - name: docker push
      run: |
        cat token.txt | docker login -u oauth2accesstoken --password-stdin https://gcr.io
        docker tag srv:latest gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/srv
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/srv
        rm -f token.txt
    - name: show docker image name
      run: docker inspect --format='{{index .RepoDigests 0}}' gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/srv
