name: "Build"
on:
  pull_request:
  push:
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: 'nix-shell --run "npm install; npm run build"'
    - name: "ls dist"
      run: ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
    - name: "ls *"
      run: ls *
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1
        SOURCE_DIR: dist
        DEST_DIR: app-develop
