name: "Frontend"
on:
  pull_request:
  push:
jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: "echo $BACKEND_URL; cd frontend; npm install; npm run build"
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist # artifact
          path: frontend/dist # from folder

  deploy-app-develop:
    name: Deploy frontend (develop)
    if: "${{github.ref == 'refs/heads/develop'}}"
    needs: build-frontend
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist # artifact
          path: dist # to folder
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          SOURCE_DIR: dist
          DEST_DIR: app-develop

  deploy-app:
    name: Deploy app
    if: "${{github.ref == 'refs/heads/main'}}"
    needs: build-frontend
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          SOURCE_DIR: dist
          DEST_DIR: app
